//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::google_auth_users::Entity as GoogleAuthUsers;
pub use super::knowledge_bases::Entity as KnowledgeBases;
pub use super::users::Entity as Users;
