//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "modality")]
#[serde(rename_all = "snake_case")]
pub enum Modality {
    #[sea_orm(string_value = "onsite")]
    Onsite,
    #[sea_orm(string_value = "remote")]
    Remote,
    #[sea_orm(string_value = "hybrid")]
    Hybrid,
}
